### ISSUE TITLE
Protected property

### ISSUE THREAD

**Issue by jeromenadaud** [PrestaShop/netreviews#7]
Error in module upgrade-7.1.3:
Cannot access protected property NetReviews:$context

**Comment by CamSi** [comment]
In reason of this bug, the module has been deactivated this morning.

**Comment by netreviews** [comment]
this bug has been solved from the version 7.1.31 (almost on 6th May)
@CamSi , could you confirm ?

**Comment by gaillafr** [comment]
Should be fixed
