### ISSUE TITLE
Error SQL Upgrade

### ISSUE THREAD

**Issue by FlYos** [PrestaShop/netreviews#8]
When I try to upgrade our module to 7.1.31, I have this SQL error with this instruction :

```php
$query[] = 'ALTER TABLE '._DB_PREFIX_.'av_orders `id_shop` INT( 2 ) NULL DEFAULT 0;';
```

*You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`id_shop` INT( 2 ) NULL DEFAULT 0' at line 1*

**Comment by netreviews** [comment]
Hi,

can you give me the actual version of our module (before the upgrade) ?


Rémi Gravelle

*Lead Developer*

Tel : +334 13 25 81 71 remi@avis-verifies.com <email@avis-verifies.com>
[image: Avis Vérifiés]

Essaie gratuit pendant 15 jours sur Avis Vérifiés
<http://www.avis-verifies.com/index.php?page=mod_inscription>

2015-05-20 10:59 GMT+02:00 Steven <notifications@github.com>:

**Comment by FlYos** [comment]
My actual version is 7.1.2

**Comment by netreviews** [comment]
Ok, I see. Can you try to uninstall the 7.1.2 and install the 7.1.31 ? You
can get it on prestashop Addons :
http://addons.prestashop.com/en/advertising-marketing-newsletter-modules/17497-netreviews.html



Rémi Gravelle

*Lead Developer*

Tel : +334 13 25 81 71 remi@avis-verifies.com <email@avis-verifies.com>
[image: Avis Vérifiés]

Essaie gratuit pendant 15 jours sur Avis Vérifiés
<http://www.avis-verifies.com/index.php?page=mod_inscription>

2015-05-20 14:12 GMT+02:00 Steven <notifications@github.com>:

**Comment by FlYos** [comment]
ok, I've uninstall and reinstall the 7.1.31 and that works, but I lost all comments :/

**Comment by netreviews** [comment]
what is your account on our platform ?

Rémi Gravelle

*Lead Developer*

Tel : +334 13 25 81 71 remi@avis-verifies.com <email@avis-verifies.com>
[image: Avis Vérifiés]

Essaie gratuit pendant 15 jours sur Avis Vérifiés
<http://www.avis-verifies.com/index.php?page=mod_inscription>

2015-05-20 16:07 GMT+02:00 Steven <notifications@github.com>:
